### PR TITLE
Mincourse use reducer

### PR DESCRIPTION
**Pull request by HourVireakboth**

### CODE REVIEW

**Comment by ghost** [comment]
you have video about flutter full stack ??

**Comment by HourVireakboth** [comment]
Yes have dear

**Comment by ghost** [comment]
bong can be to share or not if I'm a student but love app development

**Comment by ghost** [comment]
for flutter can do but is not standard

**Comment by ghost** [comment]
what name your bong telegram

**Comment by HourVireakboth** [comment]
Here dear my ***@***.***

**Comment by ghost** [comment]
no see

**Comment by ghost** [comment]
No see telegram

**Comment by skyyyse** [comment]
@testingcode78 is my telegram

**Pull request merged**
